### ISSUE TITLE
Página Boletos

### ISSUE THREAD

**Issue by Larysmo** [Larysmo/aluno-online#2]
Página de boletos não disponível

Not Found
404
NotFoundError: Not Found
    at D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\app.js:29:8
    at Layer.handle [as handle_request] (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:317:13)
    at D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:275:10)
    at D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:635:15
    at next (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Users\Larissa\Desktop\projetoGit\aluno-online-main\src\node_modules\express\lib\router\index.js:47:12)

**Comment by Larysmo** [comment]
Página desabilitada para correção
